language: objective-c
os: osx
osx_image: xcode7
install:
    - make bootstrap
before_script:
    - script/cert --import
    - make deps
script:
    - make test
after_script:
    - script/cert --remove
notifications:
  email: false
